version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api_gateway
  redis:
    image: redis:3.2.8
  gateway:
    build: ./gateway
    command: ./node_modules/.bin/nodemon gateway.js
    depends_on:
      - api
      - redis
    volumes:
      - ./config:/usr/src/config
      - ./gateway:/usr/src/app
    ports:
      - "8001:8080"
    environment:
      - GATEWAY_REDIS_URL=redis://redis:6379
      - GATEWAY_CONFIG_PATH=/usr/src/config/config.yml
      - GATEWAY_API_BASE_URL=http://api:5000
      - GATEWAY_KEY=4juA6l748gdJ7jN5112p2m0710lbkR4u
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/676612114792/api-gateway-test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  api:
    build: ./api
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    command: api_gateway api_server
    ports:
      - "8000:5000"
    environment:
      - DEBUG=True
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app:password@postgres/api_gateway
      - FLASK_SESSION_SECRET_KEY=1147C294BE7F41FF866D1457F4638
      - CSRF_SECRET=A467489B85F44B7B3582671278CCF
      - GATEWAY_KEY=4juA6l748gdJ7jN5112p2m0710lbkR4u
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/676612114792/api-gateway-test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  analytics_worker:
    build: ./api
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    command: api_gateway worker
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app:password@postgres/api_gateway
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/676612114792/api-gateway-test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
