version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api_gateway
  redis:
    image: redis:3.2.8
  gateway:
    build: ./gateway
    command: ./node_modules/.bin/nodemon gateway.js
    depends_on:
      - api
      - redis
    volumes:
      - ./config:/usr/src/config
      - ./gateway:/usr/src/app
    ports:
      - "8001:8080"
    environment:
      - GATEWAY_REDIS_URL=redis://redis:6379
      - GATEWAY_CONFIG_PATH=/usr/src/config/config.yml
      - GATEWAY_API_BASE_URL=http://api:5000
      - GATEWAY_KEY=4juA6l748gdJ7jN5112p2m0710lbkR4u
  api:
    build: ./api
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    ports:
      - "8000:5000"
    environment:
      - DEBUG=True
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app:password@postgres/api_gateway
      - GATEWAY_KEY=4juA6l748gdJ7jN5112p2m0710lbkR4u
