endpoints:
  - name: myapi
    pattern: /myapi/v1(/.*)
    target: http://localhost:8085$1
    rateLimit:
      anonymous:
        windowMs: 60000 # 1 minute
        max: 100 # 100 requests per window
      authenticated:
        windowMs: 60000 # 1 minute
        max: 300 # 300 requests per window
